---
title: "Progress Memo "
subtitle: |
  | Final Project 
  | Data Visualization (STAT 302)
author: "Kimberly Wang"
date: today

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: false
  warning: false

from: markdown+emoji 
reference-location: margin
citation-location: margin
---

::: {.callout-tip icon=false}

## Github Repo Link

[https://github.com/kimberlyxw/stats-302-final-project.git](https://github.com/kimberlyxw/stats-302-final-project.git)

:::

## Data source

This dataset was found on Kaggle.^[Ramin Huseyn (2024). Airline Customer Satisfication. Location: Kaggle [https://github.com/kimberlyxw/stats-302-final-project.git](https://github.com/kimberlyxw/stats-302-final-project.git)]

The dataset was provided by Ramin Huseyn, and it was last updated on May 6th, 2024. 

## Basic data description

This dataset was collected from an unnamed airline company, and it focuses on customer satisfaction levels. This dataset can be analyzed and used to determine how various aspects of a customer and their trip can affect their overall satisfaction levels with the airline. 

The data itself has no missingness except in the arrival delay in minutes variable. After some initial analysis, it does not seem like there is a consistent pattern in this missingness. The missingness is also relatively low, so this may be due to data collection or entry issues. Perhaps data on departure is more readily available because it might be more important for certain operations, but arrival data on the other hand is not as relevant. However, it could also be due to human error, since it is such a minor amount of missingness. In my data cleaning process, I simply removed this missingness. 

There are 129,880 observations. There are 22 columns, and out of these variables 4 are character variables and 18 are technically numeric. However, 14 of these variables are satisfaction ratings ranging from 0 to 5. 

## Why this data

This dataset primarily focuses on customer satisfaction levels, unlike other datasets that may concentrate on operational metrics for an airline While, it is important to ensure that the airplanes are running properly and well by looking at that type of data, this type of dataset allows for more people-centric analysis, which is more interesting to me.  

I also liked this dataset because there are both numeric and character variables. This will allow me to the freedom to be able to build various types of graphs. It's important to note that many of these variables are rated on a 0 to 5 scale, which segments the dataset into distinct categories. I am interested to see how this grouping will look in visualizations. 

## Visualization plan

First, I want to have a graph (or perhaps multiple) that will either be a density overlap plot or a ridge plot of the service satisfaction ratings. The goal would be to display the distribution of service ratings for each service feature like seat comfort, cleanliness, food and drink, etc. Each service will be represented in a different color for clarity. If the graph becomes too crowded, I will split the data into multiple graphs to maintain readability.

Next, I would like a graph that shows the differences in overall ratings by travel class. I would compare the average or distribution of ratings across the different travel classes like economy and business. I believe that boxplots or violin plots would be the best option to show these relationships, because they would show the differences between the medians and quartiles of the various travel classes. The challenge lies in managing the multitude of variables; I may need to select only the most pertinent categories or divide the data into a series of plots. This section would definitely not be just one box plot, but most likely a collection of them and specifically for a series of categories that are most related to differences in travel classes (like seat comfort). 

Finally, I plan to have one of the graphs that illustrates the relationship between customer satisfaction (satisfied vs. unsatisfied) and various customer demographics, such as type of travel, class, and customer type. Currently, I think a stacked bar chart would be the best option currently. This is because they can be used to compare the relative sizes of categories (like satisfied versus unsatisfied) directly and see that proportion of satisfaction across different customer segments. 

These graphs would be well-labeled and presented in a manner that is inclusion of everyone. 

## Misc 

I have created a Github link for this project. I will update my ReadMe files as I add more R scripts and folders into the project. 

