---
title: "ENTER TITLE !!!!"
subtitle: "STAT 302 Final Project"
author: "Kimberly Wang"
format: 
  revealjs:
    transition: slide
    embed-resources: true
    slide-number: true
    show-slide-number: all
execute:
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
editor: visual
---

## Introduction {.scrollable}



My GitHub Repo can be accessed through this link: [https://github.com/kimberlyxw/stats-302-final-project.git](https://github.com/kimberlyxw/stats-302-final-project.git). 


## Data {.scrollable}

::: {.panel-tabset}

### Data Information

This dataset was collected from an unnamed airline company, and it focuses on customer satisfaction levels. This dataset can be analyzed and used to determine how various aspects of a customer and their trip can affect their overall satisfaction levels with the airline. 

The data itself has no missingness except in the arrival delay in minutes variable. After some initial analysis, it does not seem like there is a consistent pattern in this missingness. The missingness is also relatively low, so this may be due to data collection or entry issues. Perhaps data on departure is more readily available because it might be more important for certain operations, but arrival data on the other hand is not as relevant. However, it could also be due to human error, since it is such a minor amount of missingness. In my data cleaning process, I simply removed this missingness. 

There are 129,880 observations. There are 22 columns, and out of these variables 4 are character variables and 18 are technically numeric. However, 14 of these variables are satisfaction ratings ranging from 0 to 5. 

This dataset was found on Kaggle.^[Ramin Huseyn (2024). Airline Customer Satisfaction. Location: Kaggle [https://www.kaggle.com/datasets/raminhuseyn/airline-customer-satisfaction](https://www.kaggle.com/datasets/raminhuseyn/airline-customer-satisfaction)]

The dataset was provided by Ramin Huseyn, and it was last updated on May 6th, 2024. 

### Why this Dataset? 

This dataset primarily focuses on customer satisfaction levels, unlike other datasets that may concentrate on operational metrics for an airline While, it is important to ensure that the airplanes are running properly and well by looking at that type of data, this type of dataset allows for more people-centric analysis, which is more interesting to me.  

:::

##  Service Satisifaction Ratings 

The next graphs look at the distribution of satisfaction rating scores across various services. 








